# The first stage
# Build React static files
FROM node:14-alpine AS build

WORKDIR /frontend/

ENV PATH /frontend/node_modules/.bin:$PATH

COPY yarn.lock /frontend/
COPY package.json /frontend/

RUN yarn --silent
RUN yarn global add react-scripts --silent
RUN yarn build

COPY . /frontend/app/
WORKDIR /frontend/app/

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
COPY --from=build frontend/build .
CMD ["nginx", "-g", "daemon off;"]