version: "3.7"

services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes: 
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    container_name: nginx-dev
    build:
      context: ./nginx_test
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443  
volumes:
  postgres_data:
  node_modules: