version: '3.7'

services:
  nginx: 
    restart: always
    container_name: nginx_adr_prod
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/default.conf
    depends_on: 
      - backend  
  backend:
    restart: always
    container_name: backend_fastapi_prod
    build:
      context: ./backendfastapi
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backendfastapi/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    container_name: postgresql_bue_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
      - POSTGRES_DB=notes
volumes:
  postgres_data: