# Generated by Django 4.0.1 on 2022-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='duck.user'),
        ),
        migrations.AlterField(
            model_name='ducks',
            name='placering',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ducks',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='duck.user'),
        ),
    ]
