FROM node:alpine as build

WORKDIR /frontend/
RUN echo Hello World!

COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./

RUN yarn

COPY ./frontend/ ./

RUN yarn build

FROM nginx:alpine
COPY --from=build /frontend/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]