# The first stage
# Build React static files
FROM node:alpine as build

WORKDIR /frontend
COPY package.json /frontend
COPY yarn.lock /frontend
RUN yarn install --silent
COPY /frontend/ ./
RUN yarn run build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
COPY --from=build frontend/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]